import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { GetServerSideProps } from 'next'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
      <h1>Home page</h1>
      </main>
    </>
  )
}


export const getServerSideProps = function(){
  // how to know if the suer is loogedin
  let userIsLogged = true
  if(!userIsLogged){
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }
  return {props:{}}
}
